### ISSUE TITLE
Error when fb-mac-messenger-monitor.sh runs

### ISSUE THREAD

**Issue by Knightfall77** [longngn/fb-mac-messenger-monitor#2]
I noticed that things weren't working right and messenger was still using over 500MB of memory, so I manually ran the fb-mac-messenger-monitor.sh script.
Got the following output: 
**./fb-mac-messenger-monitor.sh: line 7: [: too many arguments**

This is line 7: if [ $ram_usage -ge $((RAM_LIMIT_MB*1024)) ]; then

**Comment by Knightfall77** [comment]
It appears like it wants double quotes around that argument

**Comment by longngn** [comment]
@Knightfall77 It's because it doesn't sum the RAM numbers if there's multiple processes of Messenger. I fixed it and also raise the limit to 1GB. Thank you for report!
